### ISSUE TITLE
Mongo DB test failed: AttributeError: 'async_generator' object has no attribute 'add'

### ISSUE THREAD

**Issue by JhonSoto99** [shaliamekh/clean-architecture-fastapi#2]
FAILED app/tests/integration/repositories/mongodb_product_repository_test.py::test_get_by_id_success - AttributeError: 'async_generator' object has no attribute 'add'
FAILED app/tests/integration/repositories/mongodb_product_repository_test.py::test_get_by_id_not_found - AttributeError: 'async_generator' object has no attribute 'get'
FAILED app/tests/integration/repositories/mongodb_product_repository_test.py::test_add_product_success - AttributeError: 'async_generator' object has no attribute 'add'
FAILED app/tests/integration/repositories/mongodb_product_repository_test.py::test_add_product_not_found - AttributeError: 'async_generator' object has no attribute 'add'

**Comment by shaliamekh** [comment]
Hello @JhonSoto99. Thank you for reporting the issue. Although I run the the test both locally and in the cicd pipeline and can not reproduce the issue. 

Please make sure that in the `pyproject.toml` you still have the following configuration:
```
[tool.pytest.ini_options]
asyncio_mode = "auto"
```
